apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: devops      # ✅ Must match deployment namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # Target 50% CPU utilization

